version: "3.8"

networks:

  hackathon:


services:

  postgres:
    container_name: postgres
    environment:
      - POSTGRES_DB=simple-image-server
      - POSTGRES_PASSWORD=test123
      - POSTGRES_USER=image-server
#    healthcheck:
#      interval: 1s
#      retries: 10
#      test: [ "CMD-SHELL", “pg_isready” ]
#      timeout: 5s
    hostname: image-server-db
    image: postgres:14-alpine
    networks:
      - hackathon
    ports:
      - 5455:5432

  quarkus-jvm:
    build:
      # ./gradlew build -x test
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    container_name: quarkus-jvm
    depends_on:
      postgres:
#        condition: service_healthy
        condition: service_started
    environment:
      - POSTGRESQL_URL=jdbc:postgresql://image-server-db:5432/simple-image-server
      - POSTGRESQL_USERNAME=image-server
      - POSTGRESQL_PASSWORD=test123
    image: quarkus/simple-image-server-jvm
    networks:
      - hackathon
    ports:
      - 8080:8080
    
  quarkus-native:
    build:
      # ./gradlew build -Dquarkus.package.type=native -x test
      context: .
      dockerfile: ./src/main/docker/Dockerfile.native-micro
    container_name: quarkus-native
    depends_on:
      postgres:
#        condition: service_healthy
        condition: service_started
    environment:
      - POSTGRESQL_URL=jdbc:postgresql://image-server-db:5432/simple-image-server
      - POSTGRESQL_USERNAME=image-server
      - POSTGRESQL_PASSWORD=test123
    image: quarkus/simple-image-server-native
    networks:
      - hackathon
    ports:
      - 8080:8080
 