networks:

  hackathon:



services:

  postgres:
    container_name: postgres
    environment:
      - POSTGRES_DB=simple-image-server
      - POSTGRES_PASSWORD=test123
      - POSTGRES_USER=image-server
    hostname: image-server-db
    image: postgres:14-alpine
    networks:
      - hackathon
    ports:
      - 5455:5432

  quarkus:
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.native-micro
    command: [
      "-Dquarkus.datasource.db-kind=postgresql",
      "-Dquarkus.datasource.username=image-server",
      "-Dquarkus.datasource.password=test123",
      "-Dquarkus.datasource.jdbc.url=jdbc:postgresql://image-server-db:5432/simple-image-server",
      "-Dquarkus.hibernate-orm.database.generation=update"
    ]
    container_name: quarkus
    hostname: image-server-app
    image: quarkus-quickstart/getting-started
    networks:
      - hackathon
    ports:
      - 8080:8080
 